version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "@biomejs/*"
          - "@changesets/*"
          - "typescript"
          - "@types/*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
    labels:
      - "dependencies"
